name: Backend CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "admin"
          MYSQL_DATABASE: "feedify"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "oracle"
          architecture: x64

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -u root -prootpass --silent; then
              break
            fi
            echo "Waiting for database..."
            sleep 5
          done

      - name: Create Database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpass -e "CREATE DATABASE IF NOT EXISTS feedify;"
          mysql -h 127.0.0.1 -P 3306 -u root -prootpass -e "CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin';"

          # Grant all privileges
          mysql -h 127.0.0.1 -P 3306 -u root -prootpass -e "GRANT ALL PRIVILEGES ON feedify.* TO 'admin'@'%';"

          # Apply changes
          mysql -h 127.0.0.1 -P 3306 -u root -prootpass -e "FLUSH PRIVILEGES;"

      - name: Set up MySQL environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/piehme_cup" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=piehme_cup_user" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=password@123" >> $GITHUB_ENV
      - name: Build and Test with Maven inside backend folder
        run: |
          cd backend
          ./mvnw clean install
          ./mvnw clean test
        env:
          SPRING_DATASOURCE_URL: ${{ env.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ env.SPRING_DATASOURCE_USERNAME }}

          SPRING_DATASOURCE_PASSWORD: ${{ env.SPRING_DATASOURCE_PASSWORD }}